dist: xenial
language: cpp

addons:
  apt:
    packages:
      - libtool-bin
      - libmpich-dev
      - mpich

install:
  # Install ROSS
  - |
    git clone https://github.com/ROSS-org/ROSS.git ${TRAVIS_BUILD_DIR}/ci-build-deps/ROSS
    pushd ${TRAVIS_BUILD_DIR}/ci-build-deps/ROSS
    mkdir build
    cd build
    ARCH=x86_64 CC=mpicc CXX=mpicxx cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/ci-deps/ROSS ../
    make -j3
    make install
    popd
  # Install CODES
  - |
    git clone https://xgitlab.cels.anl.gov/codes/codes.git ${TRAVIS_BUILD_DIR}/ci-build-deps/CODES
    pushd ${TRAVIS_BUILD_DIR}/ci-build-deps/CODES
    ./prepare.sh
    mkdir build
    cd build
    ../configure --prefix=${TRAVIS_BUILD_DIR}/ci-deps/CODES CC=mpicc CXX=mpicxx PKG_CONFIG_PATH=${TRAVIS_BUILD_DIR}/ci-deps/ROSS/lib/pkgconfig
    # add --with-dumpi=/path/to/dumpi/install here to enable tracing with dumpi; only needs libundumpi, so can use --disable-libdumpi and --enable-libundumpi when installing DUMPI
    make -j3
    make install
    popd
  # Install OTF2
  - |
    mkdir ${TRAVIS_BUILD_DIR}/ci-build-deps/
    pushd ${TRAVIS_BUILD_DIR}/ci-build-deps/
    wget https://www.vi-hps.org/cms/upload/packages/otf2/otf2-2.1.1.tar.gz
    tar -xf otf2-2.1.1.tar.gz
    cd otf2-2.1.1
    mkdir build
    cd build
    ../configure --prefix=${TRAVIS_BUILD_DIR}/ci-deps/OTF2 CC=mpicc CXX=mpicxx --enable-shared
    make -j3
    make install
    popd
    export PATH=$PATH:${TRAVIS_BUILD_DIR}/ci-deps/OTF2/bin
    
script:
  - pushd tracer
  - make all PREFIX=${TRAVIS_BUILD_DIR}/install-test CXX=mpicc CXX=mpicxx ROSS_DIR="${TRAVIS_BUILD_DIR}/ci-deps/ROSS" CODES_DIR="${TRAVIS_BUILD_DIR}/ci-deps/CODES" SELECT_TRACE="-DTRACER_OTF_TRACES=1"
  - make install PREFIX=${TRAVIS_BUILD_DIR}/install-test CXX=mpicc CXX=mpicxx ROSS_DIR="${TRAVIS_BUILD_DIR}/ci-deps/ROSS" CODES_DIR="${TRAVIS_BUILD_DIR}/ci-deps/CODES" SELECT_TRACE="-DTRACER_OTF_TRACES=1"
  - cd ../utils
  - make
  - popd
  - |
    pushd examples/stencil4d-otf
    mpirun -np 2 ${TRAVIS_BUILD_DIR}/install-test/bin/traceR --sync=3 -- ../conf/dfly.conf tracer_config
    popd
